#!/bin/sh

LIB_DIRS="/mnt/external/0/lib /mnt/external/0/usr/lib"
TMP_HASHES=$(mktemp)

find $LIB_DIRS -type f -exec sha256sum {} \; | sort > "$TMP_HASHES"

cut -d ' ' -f 1 "$TMP_HASHES" | uniq -d | while read -r HASH; do
  grep "^$HASH" "$TMP_HASHES" | cut -d ' ' -f 3- | tail -n +2 | xargs -r rm -f
done

rm -f "$TMP_HASHES"